# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('realese', 'New release'), ('bug', 'Bug fix'), ('announcement', 'Announcement')], max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.AlterModelOptions(
        #     name='matrixannotation',
        #     options={'managed': False},
        # ),
        # migrations.AlterModelOptions(
        #     name='matrixprotein',
        #     options={'managed': False},
        # ),
        # migrations.AlterModelOptions(
        #     name='matrixspecies',
        #     options={'managed': False},
        # ),
    ]
