# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170617_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsAndUpdate',
            new_name='Post',
        ),
    ]
