# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170617_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Update', 'Update'), ('Bug fix', 'Bug fix'), ('Announcement', 'Announcement'), ('Other', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
